# Default project demi app. Created by Artem Khomenko 26 Feb 2021

[globals]
[globals.world]
width = 1000 # number of dots in width, max 30_000
height_ratio = 0.4583 # proportion for height, for Mer—Åator 24:11 or 0.4583
resolution = 0.1 # number of dots calculated for each tick. Actually determines the speed of processes relative to the movement of the sun

[elements]